title: Developer's Blog | Adam Pajkert ( pajadam )
description: >
  Blog about everything, especially coding and technologies.
  Written by young developer from Poland. Adam Pajkert ( pajadam ).
altname: Adam Pajkert | pajadam
author: Adam Pajkert
baseurl: ""
url: "https://blog.pajadam.me"

analytics_id: "UA-77141286-4"

markdown: kramdown

plugins:
  - jekyll-press
  - jekyll-paginate

paginate: 10
paginate_path: "/posts/:num/"

permalink: /posts/:title/

jekyll-press:
  exclude: [ 'sitemap.xml', 'robots.txt' ]
  js_options: {}
  css_options: {}
  html_options: {}

exclude: [ "LICENSE", "README.md", ".gitignore", ".gitattributes", "Gemfile", ".bundle" ]